---
switchhostname: generic

interfaces:

  - port: ge-0/0/0
    description: "Some description"
    family: ethernet-switching
    mode: access
    vlans:
      - vlan0

switchvlans:
  - name: vlan0
    l3-interface: ge-0/0/0
    id: 1
virtualchassis:
services: